#! /bin/sh
### BEGIN INIT INFO
# Provides:          satnetprotocol
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop GHServer server
### END INIT INFO

logger "satnetprotocol: Start script executed"
# Test values
SATNET_PROTOCOL_PATH="/home/sgongar/Dev/protocol"
export PYTHONPATH="$SATNET_PROTOCOL_PATH:$PYTHONPATH"

case "$1" in
  start)
    logger "satnetprotocol: Starting"
    echo "Starting SatNet protocol..."
    source "$SATNET_PROTOCOL_PATH/.venv/bin/activate"
    twistd -y "$SATNET_PROTOCOL_PATH/server_amp_daemon.tac" -l "$SATNET_PROTOCOL_PATH/server_amp_log.log" --pidfile "SATNET_PROTOCOL_PATH/twistd.pid"
    ;;
  stop)
    logger "satnetprotocol: Stopping"
    echo "Stopping SatNet protocol..."
    kill `cat $SATNET_PROTOCOL_PATH/twistd.pid`
    ;;
  *)
    logger "satnetprotocol: Invalid usage"
    echo "Usage: /etc/init.d/satnetprotocol {start|stop}"
    exit 1
    ;;
esac

exit 0
